### ISSUE TITLE
Ghostery extension blocks network calls to *.trustarc.com/* and *.truste-svc.net/* when Ad blocking is enabled

### ISSUE THREAD

**Issue by hyebahi** [ghostery/ghostery-extension#1136]
### Description

Ghostery extension blocks network calls from *.trustarc.com/* and *.truste-svc.net/* when Ad blocking is enabled, even though [TrustArc is categorized as Essential in the WTM database](https://whotracks.me/trackers/trustarc.html). This is blocking Privacy Policy content for different sites, as most sites rely on this script to control third-party trackers.

This is related to the issue happening for OneTrust:
https://github.com/ghostery/ghostery-extension/issues/804

### Expected Behavior

Allow network calls required to load the TrustArc CMP.

### Actual Behavior

Scripts are being blocked, and users are unable to set their preferences in the TrusArc CMP. This behavior happens on any websites using TrustArc CMP.

### Steps to Reproduce

1. Navigate to trustarc.com
2. CMP banner doesn't load, or the Cookie Preferences link at the footer is not available
3. Users are unable to set their preferences

### Versions

+ Browser: Google Chrome Version 112.0.5615.137 (Official Build) (x86_64)
+ OS: macOS 13.3.1 (22E261)

**Comment by hyebahi** [comment]
Hi @philipp-classen 

I hope you're doing well. I wanted to reach out because I noticed that you had previously worked on a similar fix for #804. I was wondering if you could kindly lend a hand with this one as well? Your expertise would be greatly appreciated!

Thank you in advance for your assistance

Best,

**Comment by chrmod** [comment]
Dear @hyebahi - thank you for rising this issue. Ghostery intention is to allow users opt-out from tracking automatically with our feature [Never-Consent](https://www.ghostery.com/blog/never-consent-by-ghostery).
To make this possible, CMP requests cannot be blocked and dialog boxes cannot be hidden by the adblocker filters. That means we need to know those filters in the first place. 
I've create a first list for filters for TrustArc in Ghostery Tracker Database. If done correctly, Ghostery will stop applying those filters. 
Please help us keep this list correct and complete: https://github.com/ghostery/trackerdb/pull/17 


BTW. I cannot find any rule that blocks truste-svc.net, are you aware of any?

**Comment by hyebahi** [comment]
Hello, @chrmod! 
Thank you for your assistance with the fix. 
I will keep an eye on the mentioned pull request to confirm it is working correctly. 
To avoid any potential blocking, I have included the domain truste-svc.net in the request, as it is called when the CMP modal window opens. 

Moreover, I have updated the autoconsent verification to verify the completion of opt-out: https://github.com/ghostery/autoconsent/pull/38. 

I hope you have a great week ahead.

**Comment by hyebahi** [comment]
Hi @chrmod 
I hope this message finds you well.
Do you have any details about the next release for trackerDB? I am waiting for it to validate this fix.
Please let me know if I can be of any assistance.

Thank you for all your help

**Comment by hyebahi** [comment]
Hi @chrmod 
Thanks for your help again. I just tested on my end, but it doesn't seem to have updated the database. I'll keep testing during the day. I'll make sure to keep you posted.

**Comment by hyebahi** [comment]
Hi @chrmod 
The changes don't seem to be propagated to the Ghostery extension. Any thoughts?
![image](https://github.com/ghostery/ghostery-extension/assets/14881995/da9a9ab6-907e-4b6f-b70d-fb67fac1f670)

Thanks and have a great weekend!

**Comment by chrmod** [comment]
@hyebahi I did some testing and even though it may look nothing changed I think all works as expected. The goal was to prevent Ghostery from blocking TrustArc requests and if you inspect the network you should see only one kind of requests being blocked and it is the `/log` endpoint `https://consent.trustarc.com/log?domain=trustarc.com` 
Those kind of request we normally categorise as site analytics, and would typically block by default.
But all other trust arc request (required to load the CMP) should work perfectly well.

Can you please share a website example so we can verify if all works as expected?

**Comment by hyebahi** [comment]
Hello @chrmod,

I have contacted the TA engineering team regarding the /log endpoint and it appears that it is utilized for audit purposes. CMP clients can leverage the information to respond to DSAR and monitor their instance usage. As a CMP is a necessary tool for the website, would it be possible to include the endpoint in the allowed list?

I would appreciate your input on this matter.

Best regards.

**Comment by hyebahi** [comment]
Hi @chrmod 
Can you share your thoughts on whether we can proceed with allowing access to the /log endpoint?
Many thanks

**Comment by chrmod** [comment]
Have done some testing and noticed that it was another cosmetic rule that was blocking the  cookie consent banner at https://trustarc.com/ - specifically [`###consent_blackbar`](https://github.com/ghostery/trackerdb/blob/bdb28757552af6ac46c9ad1c0cb7f5de70f24294/db/patterns/tealium_consent.eno#L11)

Once added to Tracker Database and rollout with latest adblocker filters I can see the popup at trustarc.com and can confirm that Never-Consent can work correctly.

@hyebahi Does it work for you as well? 

I've tried to compare state of cookies to normal user interaction and they look similar.

**Comment by hyebahi** [comment]
Hi @chrmod 
The problem is with the Ad-Blocking feature. When it is turned on, the CMP script aborts the loading due to net::ERR_BLOCKED_BY_CLIENT.
I've attached a quick recording of the issue.
[Ghostery Test.webm](https://github.com/ghostery/ghostery-extension/assets/14881995/01856cfd-77f3-4b20-99f9-6d7edaaa0fd3)

**Comment by chrmod** [comment]
Dear @hyebahi 

AFAICT the banner shows and works fine. Are we mixing two different problems? The issue that was hiding the banner does not occur any longer.

At Ghostery, we block all forms of tracking by default because we believe that our users deserve the highest level of privacy and control over their data. We understand that it is impossible to know how the collected user data will be used or changed over time, so we do not trust anyone with it, even the good players.

We appreciate that TrustArc has a proper split of API endpoints, which allows us to block the /log requests without affecting the functionality of the CMP. We respect the value of telemetry and other forms of analytics that /log can provide, but we also adhere to the spirit of GDPR that no user data can be collected without user consent. (In this case, the IP address is being shared, at the very least.)

For publishers, the most important feedback is that users have opted out from tracking. This is what Ghostery’s feature Never-Consent provides. This is also why Ghostery does not block CMPs, so we can use them to communicate to publishers that we don’t want to be tracked.

We believe that good-players like TrustArc are helping to make the internet a more private place and we hope that the wider community realizes that privacy comes with some compromises. Ghostery always prioritizes users’ privacy over publishers’ business.

In line with our philosophy: Specifically, we allow TrustArc CMP to function, but generally we also block requests specified by community blocklists. In this case, the triggering rule ||trustarc.com/log? comes from EasyPrivacy. Their repo is the best place to discuss if /log should be blocked or not.

Thank you very much for pushing this topic forward! LMK if you have any further questions.
