### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by maverick74** [ghostery/ghostery-extension#12]
This is not exactly a bug, but something i believe worth working on.

I understand that comparing addons is not exactly your intentions, but the fact is that users will do so even if you don't want them to.

I've been using ublock origin a few years already. After the switch to Ghostery i immediately noticed it slowed down my browser.
Now, the tech behind Ghostery is attractive (AI and so on), but ublock is also a great content blocker. In fact enough for most users.

**My suggestion** is compare Ghostery with other top blockers (ublock orgin, adblock plus, adblock edge, etc) and work on it so that it became at least as lite as the lightest competitor

**Comment by christophertino** [comment]
It's a fair point and it's something we are aware of.  The comparisons are a bit tricky since Ghostery is inherently heavier than some of the competing products you mentioned.  Our ad-blocker module runs the same EasyList filters as other extensions, and on top of that we’re pattern checking against the Ghostery tracker list and running our heuristic anti-tracking.  For all that overhead we feel Ghostery is still pretty performant, but of course there’s always room to improve. 

I agree that content blocking may be sufficient for some users, and that’s perfectly fine.  Our focus continues to be on those who want privacy protection.  It’s a small but important distinction, in that the latter tends to accept a heavier application (or often multiple apps) to ensure they are privacy safe.  That said, the performance impact of running Ghostery with all modules active and trackers blocked should always be net positive.  It’s really helpful if any users could let us know when that's not the case (see  #11).

I think this is a great discussion topic, and honestly it’s one of the positive interactions we hoped to gain when we open-sourced.  We’re going to be adding some performance markers into the code over the next couple months to help us baseline new features and sniff out any pain points. We’re also toying with a “lite” version of Ghostery with a leaner feature set and simplified tracker protection.

**Comment by maverick74** [comment]
I liked very much of the recent "Adblockers Performance Study" ( https://whotracks.me/blog/adblockers_performance_study.html )

Thank you :)

**Comment by christophertino** [comment]
Thanks! Shout out to @remusao for all of his work making these performance improvements and putting the study together.  We'll be rolling out these updates in our 8.4 release.
