### ISSUE TITLE
collector-hpn.ghostery.net

### ISSUE THREAD

**Issue by zeropi2021** [ghostery/ghostery-extension#1258]
Hello,

I observe in the Pi-Hole logs constant queries for collector-hpn.ghostery.net
Which is blocked in two lists. What does this address do and why does it try to poll twice a minute on average?
Allowing this domain does not eliminate queries, it only increases the time interval between them.

In opt in options everything is unchecked.

Any reasonable explanation?

**Comment by chrmod** [comment]
hi @zeropi2021 - thank you for reporting the issue. This is expected behaviour and this endpoint is essential for Ghostery being able to provide its features. We use it to gather reports about trackers online. It is covered by out privacy policy https://www.ghostery.com/privacy-policy#IV-WhoTracksMe
We visualise the data at whotracks.me
Hope this helps. Let me know if you have any other questions, or best please send email to support@ghostery.com with a link to this issue.

**Comment by Bjelko** [comment]
i removed Ghostery extension from chrome a while /Month+/ago but still having fresh requests in pihole logs
