### ISSUE TITLE
Persistent Permission Pop-up on macOS Sonoma (v14.0) in Safari (v17.0)

### ISSUE THREAD

**Issue by MadhavVij** [ghostery/ghostery-extension#1293]
**macOS Version:** 14.0 (23A339)
**Safari Version:** 17.0 (19616.1.27.111.16)

**Issue Description:**

Ever since I upgraded to the RC build of macOS Sonoma, I have been encountering an incessant pop-up notification (attached screenshot) that persists despite my chosen option (Allow for one day, Always allow, Deny). This recurring pop-up specifically requests permission for unsplash.com.

I have attempted to resolve this issue by removing the website from my Safari extension settings, but the problem persists. I'm seeking assistance in resolving this persistent permission pop-up, as it disrupts my browsing experience with an unwanted and frequent interruption.

The pop-up notification with the following message:
```
The extension "Ghostery" would like to access unsplash.com/.
This extension would be able to read and alter webpages and see your browsing history on this website. This could include sensitive information, including passwords, phone numbers, and credit cards.
You can change this later in the Websites section of Safari Settings.
```

![Screenshot 2023-09-17 at 20 52 24](https://github.com/ghostery/ghostery-extension/assets/8644248/1e0d65e9-3eda-4772-8d45-9574ad2d2a7f)

**Comment by smalluban** [comment]
I can confirm the bug on Safari Technology Preview Release 179 (Safari 17.0, WebKit 18617.1.8.1), running on macOS Ventura 13.5.2. The bug is related to the Safari version (not the OS).

However, the permission process is outside of the extension itself. We are not in control over it. The extension sets its required permission in the `manifest.json` file, and that's all we do. The bug is definitely there, but it is on the browser side and we cannot fix it.

The best way is to report an issue directly to Apple. You can do that directly from the Safari menu: 
<img width="438" alt="Zrzut ekranu 2023-09-25 o 09 56 04" src="https://github.com/ghostery/ghostery-extension/assets/1906677/9480fc8a-77f2-44bc-be82-99d7032f35bf">

**Comment by smalluban** [comment]
@MadhavVij Feel free to re-open if there is something else related to the problem.

**Comment by smalluban** [comment]
@MadhavVij We have submitted issue report to Apple (it looks that this feature is available in Safari Technology Preview only - directly in the browser).

The problem is related somehow to visiting the unsplash.com. For now, we can only recommend to clear out the data from the unsplash.com (if it is fine for you):

Go to Safari -> Settings -> Privacy -> Manage Website Data, find unsplash.com and remove data. After reloading the browser, the problem should be gone (at least if you do not visit unsplash.com again).

<img width="688" alt="Zrzut ekranu 2023-09-29 o 10 02 04" src="https://github.com/ghostery/ghostery-extension/assets/1906677/085ea0d5-ee7a-444d-8c8e-0554b6ffff8d">

**Comment by MadhavVij** [comment]
Thanks for filing the report and identifying the issue. Deleting the website data for unsplash helped, but now it's a different website that's giving me the same error.
Hope the next Safari update fixes it 🤞🏻

**Comment by gkindrick** [comment]
@smalluban's fix worked for me, without the issue @MadhavVij experienced.
_MacOS 14.0 / /Safari 17.0 / Ghostery 10.2.0_

**Comment by beingmrkenny** [comment]
Thanks for the workaround and submitting the issue.

**Comment by dmbuil** [comment]
Hi!
If it is of some use, the issue still persists on **Safari 17.2.1** with **Sonoma 14.2.1**. At least, the workaround works well :)

**Comment by tcilloni** [comment]
Safari 17.4 and Sonoma 14.4 issue persists, but thanks for the workaround!

**Comment by smalluban** [comment]
@tcilloni Thanks for the update.
