### ISSUE TITLE
[Ghostery Control Panel] grey out Ghostery icon when site paused

### ISSUE THREAD

**Issue by mdsandu** [ghostery/ghostery-extension#1330]
![Image](https://github.com/ghostery/ghostery-extension/assets/116146386/16f50bc0-d3fc-41ef-bc7d-10d2adb2fca8)

**Comment by kalinme** [comment]
@smalluban @mdsandu can you see any other states: https://www.figma.com/file/GIWeYHGf3bUQzCd3LK9VmL/Ghostery-Panel?type=design&node-id=1886%3A25514&mode=design&t=ukLWinXV64BHseeR-1

in my browsers icon for paused protection or disabled blocking is still blue

**Comment by smalluban** [comment]
After a while of struggle why Safari still shows an icon in "bluish" way, there is interesting article about the issue:

https://lapcatsoftware.com/articles/2021-7-7.html

In short, Safari adds on top of the icon the "highlight color in System Preferences" (which by default is kind of blue) if the icon seems to match a "template" thing - its kind of one color on transparent background (I checked and for example if icon is yellow, than it's fine, but any shade of gray goes to this "template" thing).

In our case, by the coincidence, when we switch to paused, the icon is made gray, so Safari applies that "blue" filter on top of it. If you look closely, the icon has bluish eyes - so it is not the same as default. 

However, if the icon is a wheel, Safari does not recognize it as a template because it has multiple colors on it.
