### ISSUE TITLE
Unable to change Privacy protection settings

### ISSUE THREAD

**Issue by hyebahi** [ghostery/ghostery-extension#1641]
After the new update, the toggle buttons in the privacy settings are disabled and cannot be changed.
Google Chrome 125.0.6422.141
Mac OS

Is this the intended behavior?

![Screenshot 2024-06-06 at 2 35 22 PM](https://github.com/ghostery/ghostery-extension/assets/14881995/a894abf5-c299-4f9c-bedd-b62697e3bc6b)

Thank you

**Comment by chrmod** [comment]
Hi @hyebahi - thank you for reporting the issue. This is in fact an expected behaviour that we introduce to help a group of users that was fiddling with Ghostery setting, not realising the with ad-blocking disabled their privacy is at risk. That said, with this update we have already heard from many other users that they expect more control. We hear you and are in process of finding a solution that would be most usable for all user groups. Stay tuned for the updates.

Feedback like yours is very important now that we rollout new version of Ghostery. Thank you for being a voice of Ghostery Community!

**Comment by smalluban** [comment]
Fixed with #1642

**Comment by philipp-classen** [comment]
Reopened: this issue has been reported by many users, we can keep this issue open until the releases are live:

- [ ] Chrome
- [ ] Edge
- [ ] Opera

We will push a release for review today. From past experience, it should be out today or early next week.
