### ISSUE TITLE
Brave: This extension may be corrupted

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1672]
From Windows 10 / Brave Version 1.67.116 Chromium: 126.0.6478.71

![image (1)](https://github.com/ghostery/ghostery-extension/assets/1228153/294e0cc9-e32f-4698-a03b-6743ae9b9813)

**Comment by philipp-classen** [comment]
We could confirm, but we have no reliable way to reproduce. It could be related to similar reports that we got occasionally in Opera and Edge after migrating to Manifest V3. One observation is that it proved difficult to reproduce by installing Ghostery in a fresh profile. The profiles that were affected were ones that have been used for a while. Perhaps rare events like extension updates or awaking from suspend mode may trigger it.

From our understanding, it is not related to the extension code itself but by the browser. It does not appear to be a wide-spread problem; but since we had report also on Opera and Edge starting after the Manifest V3 migration, it could be a problem in the shared Chromium code base. Ghostery 10 has been rolled out to Chrome only recently, which might explain why we did not get reports specifically for Chrome yet.

**Comment by GRadziejewski** [comment]
I have two separate Windows 10 operating systems. 

One is on a virtual machine - here I have a corrupt add-on installation (user profile: [https://we.tl/t-KaGfhYAYgC](https://we.tl/t-KaGfhYAYgC?trk=TRN_TDL_05)). 99% of the time, I save the system as it is. I usually reset it during updates or problems with the OS itself.

The other system I shut down every time I stop using it. Here everything works fine.

**Comment by chrmod** [comment]
Should be fixed by https://github.com/ghostery/ghostery-extension/pull/1725
