### ISSUE TITLE
Google Tag Manager tracker URLs are blocked

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1749]
**Description**
After a new installation of the add-on, the Google Tag Manager tracker is blocking URLs. It should not.

**Steps to Reproduce**
1. Install the add-on
2. Open https://www.fandom.com/
3. Look for any tracker from an essential category, for example Google Tag Manager
4. Look at the tracker URLs - they are blocked (but they should not)

![image](https://github.com/user-attachments/assets/78cc65bd-9ebd-43e8-bcd5-a0ff2e689c80)

**Expected results**
When the tracker is trusted, URLs must be observed.
When the tracker is blocked, URLs must be blocked.

**Versions**
```
Browser: Chrome 126.0.6478.127
OS: Windows 10
GBE 10.3.13
```

**Comment by philipp-classen** [comment]
The fixes DNR list has since entry (locally reproduced, so the ID might change):

```
  {
    "id": 1507,
    "action": {
      "type": "block"
    },
    "condition": {
      "urlFilter": "||googletagmanager.com/gtm.js",
      "initiatorDomains": [
        "fandom.com"
      ],
      "isUrlFilterCaseSensitive": false
    },
    "priority": 1000201
  }
```

Where this rule comes from, is not clear yet.

**Comment by philipp-classen** [comment]
In the Chrome release, it is this rule (fixes DNR list):
```
  {
    "id": 1501,
    "action": {
      "type": "block"
    },
    "condition": {
      "urlFilter": "||googletagmanager.com/gtm.js",
      "initiatorDomains": [
        "fandom.com"
      ],
      "isUrlFilterCaseSensitive": false
    },
    "priority": 1000201
  },
```

**Comment by philipp-classen** [comment]
To sum up our findings:
TrackerDB classifies the request as Google Tag Manger and puts it in the essential category: https://github.com/ghostery/trackerdb/blob/e64452693549ec9d9b0fab9985b345655b7010e3/db/patterns/google_tag_manager.eno#L8

That explains why the requests are being shown as trusted in the UI. It should also result in an exclusion rule to allow these requests. However, it is an edge case, because there is a high priority rule on the "unbreak" list:
```
||googletagmanager.com/gtm.js$important,domain=fandom.com
```

This rule has `important`, so it will always take precedence on `fandom.com`. Even higher than the exclusion from TrackerDB.

Since blocking the request is intentional here - otherwise, it would not be on the unbreak list - the behavior of the adblocker is correct. Arguably, the UI is a bit confusing, since blocked requests are now being shown in a trusted category. On the other hand, it is most likely a rare situation. Maybe the UI could detect such cases, but it is not clear if this extra complexity is justified. (Open question.)

But in a nutshell, we have a request that according to TrackerDB is critical and should generally never be blocked. But then, we have a concrete example, where the community decided that it is critical to block it to *avoid* breakage. Blocking to avoid breakage, is fairly uncommon; normally, it is the opposite (blocking increasing the change of breakage). At least, it is likely that situation like on fandom.com should be rare.
