### ISSUE TITLE
Cannot log into freecharge when ghostery is active.

### ISSUE THREAD

**Issue by chetanbasuray** [ghostery/ghostery-extension#192]
When trying to log into Freecharge website with ghostery switched on, the website says something went wrong and does not allow a log in, but with Ghostery turned off, the log in is successful.

### Expected Behavior 

Log in should be successful with Ghostery turned on.

### Actual Behavior 

Log in unsuccessful.

### Steps to Reproduce

1. Go to https://www.freecharge.in/desktop/
2. Try logging in with a user name and password and Ghostery active. One of the accounts from http://bugmenot.com/view/freecharge.in might work as a means of testing.
3. The log in will fail.
4. Try logging in the Ghostery turned off, the log in should succeed.

+ Browser: Chrome
+ OS: MacOS HighSIerra

**Comment by christophertino** [comment]
I messed around with this a bit and it looks like the login API call to `https://www.freecharge.in/api/v2/identity/signin/user` has some  third-party dependencies.  If It allow the Google Tag Manager, Adobe Dynamic Tag Manager and Omniture trackers on this site, the login succeeds. 

We can add compatibility exceptions for these trackers so that they are automatically unblocked on this site for users with Smart Blocking enabled.
