### ISSUE TITLE
implement alternative in-panel Contribution message with asking for reviews

### ISSUE THREAD

**Issue by mdsandu** [ghostery/ghostery-extension#1998]
link to appropriate store per extension version:

- [ ] [Opera](https://addons.opera.com/en/extensions/details/ghostery/)
- [ ] [Chrome](https://chromewebstore.google.com/detail/ghostery-tracker-ad-block/mlomiejdfkolichcflejclcbmpeaniij)
- [ ] [Firefox](https://addons.mozilla.org/en-US/firefox/addon/ghostery/reviews/)
- [ ] [Edge](https://microsoftedge.microsoft.com/addons/detail/ghostery-tracker-werbe/fclbdkbhjlgkbpfldjodgjncejkkjcme) 
- [ ] [Apple](https://apps.apple.com/us/app/ghostery-privacy-ad-blocker/id6504861501)
- [ ] create automated test if possible
- [ ] add redirects to stores through our website to count clicks on the message
- [ ] add rotation (random) 50/50 with current contribution message

**Comment by mdsandu** [comment]
linked to: https://github.com/ghostery/collaboration-charly/issues/14

**Comment by smalluban** [comment]
@mdsandu As you assigned me, I suppose that issue is ready to be implemented, but I cannot find the final copy in the above description, and if required a link to the updated design of the panel.

The e2e test for that feature adds limited gain, as the notification is just a text with a link, and we can only test it in Chrome and Firefox. Also, to make it work, we would have to fix the URL in e2e too, but this URL may change in the future.

**Comment by mdsandu** [comment]
it's not - I just opened the ticket to not forget - will update and add the deadline once it's ready for implementation

**Comment by mdsandu** [comment]
https://www.figma.com/design/MX1jFfCA1deyGljcVKQQzE/Ghostery-Panel-Design-System?node-id=22-6763&t=7wso365DFJN8v3vs-1

**Comment by mdsandu** [comment]
@philipp-classen can you pls provide the redirects discussed [here](https://ghostery.slack.com/archives/C03M3895D71/p1730810561935759) for tomorrow 7.11, so @smalluban can implement?
the landings are in the fist comment on this ticket - [here](https://github.com/ghostery/ghostery-extension/issues/1998#issue-2618414948)
