### ISSUE TITLE
Bug Report: Cookie Banner is being blocked

### ISSUE THREAD

**Issue by PeterHdd** [ghostery/ghostery-extension#2041]
I'm not sure if it's a bug or if it's intended,  but I'm trying to use the following repository for the cookie consent banner:

https://github.com/orestbida/cookieconsent

I noticed whenever the ghostery extension is enabled, the banner appears but immediately disappears, so the user is unable to either accept or reject. Is this intended?

Then I also noticed it happens with another bunch of websites, but some websites the banner is appearing normally even with ghostery extension is enabled. So the question here comes, if this is intended how do we bypass it then?

**Comment by seia-soto** [comment]
Hi @PeterHdd ,

Our Never Consent functionality aims to "reject" cookie banners if supported. For the wider coverage, we may involve other techniques that may just hide the cookie banner. In this case, the resulting action (.e.g. loading of tracking script) will depend on websites' code. For those cases, it can be neutralized since we're also blocking tracking scripts directly.

If you want to disable the functionality for a while to test the use of that library, you can disable "Never Consent" from our extension settings (click Ghostery icon -> click "Never Consent" -> disable "Never Consent" -> refresh the webpage in about a second).

Just a note regarding the functionality, We're accepting reports of unsupported cookie consents from https://github.com/ghostery/broken-page-reports/issues/new/choose or our support page. Also, feel free to report if you don't think the consent is correctly "rejected" by our extension in the future.
