### ISSUE TITLE
Large download on every start

### ISSUE THREAD

**Issue by Benjamin-Markson** [ghostery/ghostery-extension#323]
Recently, I've been trying to love (and trust) Ghostery again. I've mainly only used it up to version 5 (around which time I felt it lost its way). Anyway, Ive now been using version 8, and it is nicely done. A part from the Enhanced Anti Tracking which doesn't seem to put anything in the detailed view it provides useful visibility on what it's doing. However, there is one thing that's bothering me and I'm wondering if it's a feature or a bug.

At browser start up I see Ghostery making an awful lot of connections to the internet:

 cdn.ghostery.com
 cmp-cdn.ghostery.com
 api.ghostery.net
 cdn.ghostery.net (3 times)
 collector-hpn.ghostery.net

One of these fetches a very significant amount of data on every start. Doesn't matter if you close Firefox and immediately restart, down it all comes again. Uncheck the: Enable automatic updates from the Ghostery tracker library... and  it still comes down each time. It feels either very inefficient, or like a bug.

I'd be interested to know what these many domains are for and whether there is any documentation on the various connections being made at start up?

Cheers.

Browser: Firefox
OS: Windows
Ghostery: 8.3.0

**Comment by philipp-classen** [comment]
Hi Benjamin,

For me, the extension downloads about 4.15 KB (actual transferred size) when I restart Ghostery. Both on Firefox and Chrome (tested on Linux). Is this about the same size that you see?

About 2.6 KB (compressed) is for `https://collector-hpn.ghostery.net/config`, the config of the system used for anonymized data transfer. For example, if you allow Ghostery to send Human Web messages, it will be sent through this channel. At the moment, we are lacking in documentation but I hope we can improve on that in the near future (related: https://github.com/cliqz-oss/browser-core/issues/67).

The reason why the `/config` request is not cached is that we currently use the timestamp returned by the server to detect drift on the local system clock. (A correct clock is important for anonymity, as otherwise, we could link messages based on the error in the clock.)

But maybe you meant another request. Do you remember which request it was that fetched significant amounts of data? Note that you can ignore all requests that were served from disk cache.
