### ISSUE TITLE
ghostery stopped working (greyed out) in Cliqz Browser

### ISSUE THREAD

**Issue by gmeades** [ghostery/ghostery-extension#395]
### Description

When I start the Cliqz (Firefox based) Browser, ghostery does not run.  It has stopped working, and is greyed out.  Removing the ghostery addon and reinstalling it makes it work initially, only to have it fail again after being in use for a while.  There seems to be no way to manually refresh or restart the addon.  

### Expected Behavior 

Ghostery icon should be active, with the icon that appears being blue in color to show it is working, and a number to show the number of ads it has blocked appearing in the upper left or right side of the icon.

### Actual Behavior 

When Cliqz browser is started, ghostery icon is greyed out. The addon is inactive, and does not work.  Left-clicking the ghostery icon brings up an empty (blank) usage/information/management window, with no information at all.

### Steps to Reproduce

1. Install Ghostery addon to Cliqz Web Browser
2. Notice Icon appears blue and s active.
3. Restart Cliqz Web Browser
4. Notice Ghostery icon is now greyed out, inactive, and not working.  If Ghostery icon is working upon restart of browser, simply leave it alone for a while (an hour or two, perhaps) notice ghostery icon is greyed out, inactive, and not working.
5. Left click greyed out ghostery icon, and the details/information/management window will open but will be blank and empty, containing no information at all. 
6. There is no way to restart or refresh ghostery addon other than restarting cliqz browser and hoping ghostery will work once again, at least temporarily.

### Versions

+ Browser: Cliqz 1.27.1 (67.0.1 + 1.37.0) (32-bit)
+ OS:  Windows 7 64-bit SP1
+ Node:
+ NPM:

**Comment by Eden12345** [comment]
Hey @gmeades, thanks for reaching out about this. We haven't been able to reproduce this issue on our end after some initial testing. I know you mentioned that you've tried uninstalling and reinstalling the Ghostery extension — have you tried uninstalling and reinstalling the Cliqz browser itself?

**Comment by gmeades** [comment]
No, I didn't try uninstalling and reinstalling the 32-bit cliqz browser 
as I didn't want to lose all of my configuration,
bookmarks, history, etc. and the only thing not working or ever giving 
me any problems has been the ghostery addon
going inactive on me.

What I did do however, and seems to have worked as far as fixing 
ghostery, was I installed the 64-bit version of cliqz
on my computer.  Ghostery worked as soon as it was installed, and has 
continued working for the past 3 days
or so with no problems at all.

The only problem with upgrading to the Cliqz 64-bit version is that it 
did not adopt my settings from the 32 bit version
as I had hoped it would, and there doesn't seem to be any way to 
automatically import these items from Cliqz 32-bit
into cliqz 64-bit.  So, I have both cliqz browsers on my machine, with 
all my bookmarks, configuration, history, etc in
the 32-bit version, but using the 64-bit version for all of my current 
browsing needs while I try to figure out how to get everything exported 
and reimported into the 64-bit version, or if that doesn't work out, 
undertake the tedious process of manually copying everything over to the 
more stable 64-bit version...

One possibility to make the transfer of all my history, settings, 
configuration, etc. as easy as possible would be to copy some
files or folders from the cliqz folder from the 32-bit version (under 
"Program Files (x86)" to the cliqz folder for the 64-bit version (under 
"Program Files") on my Win 7 64-bit machine, but I don't know which 
files or folders contain this information in order to just copy them 
over, or if that's even possible as the 32-bit version files themselves 
may not be compatible with the 64-bit version...

So, doing a lot of googling and reading at the moment... :-p

**Comment by Eden12345** [comment]
Thanks for following up with more info about the steps that you've taken here. At the very least, you should be able to transfer bookmarks from your 32-bit version to your 64-bit version by following the steps outlined here: https://cliqz.com/en/magazine/tutorial-import-bookmarks-cliqz-browser. You'll need to export them as HTML from the 32-bit version and import them as such into the 64-bit version. Also, depending on your version of Cliqz, the bookmark icon in your toolbar may look like this screenshot (rather than the screenshot in the article):

<img width="389" alt="Screen Shot 2019-06-19 at 4 56 34 PM" src="https://user-images.githubusercontent.com/32471984/59800207-fe9cc900-92b3-11e9-9204-470c16f1c6e5.png">

Please let me know if that helps at all. I'll tag in @luciancor as well to see if he can shed any more light on what's going on here.

**Comment by gmeades** [comment]
Thanks Ethan...  that got my bookmarks moved over...
I was able to import my login credentials and plugin's from chrome and 
firefox that I still have on the machine...
and manually changed most, if not all, of the configuration options in 
settings...

Which I think pretty much only leaves my browser history to deal with 
now....
I generally have a pretty substantial history as I do research on 
things, so they're kind of like a library, with sections
by subject, so, it would be great if there was a way to export that from 
the 32 bit version and import it into the 64-bit
version...

Almost there....  just need to figure out how to get that history moved 
over...  :-p

**Comment by alver-cliqz** [comment]
Good day. I'm a Cliqz desktop browser developer, so I will try to help you.

First of all, be default all user information saved in profiles folder here: %AppData%\CLIQZ. Both 32 and 64-bit versions use the same location to work with user's information.

Can you please do next:
1. Start browser, do as least action as possible and wait till Ghostery icon will be grey.
2. Open Browser Toolbox (with Ctrl+Shift+Alt+I shortcut or from menu bar, press Alt, choose Tools -> Web Developers -> Browser Toolbox). Will appears a new window and small dialog, asking to allow connection. Allow it.
3. In new window (this is Browser Toolbox) open a "Console" tab (on top of window) and copy all log messages from there (there must be no any personal information.
4. Send it to me directly (alexander@cliqz.com) for checking or share in any other way your prefer.

This is first step, I will try to understand where the problem is.
