### ISSUE TITLE
Application with identifier 'ghostery' was not found in the directory - Azure AD

### ISSUE THREAD

**Issue by TheAifam5** [ghostery/ghostery-extension#459]
### Description

I am developing an application where the tokens are refreshed in background using IFRAME. Ghostery does some things which makes the whole site to redirect to OAuth2 authentication page with `&client_id=ghostery` query. It happens when the token is going to be refreshed.
My application uses AzureAD.

### Expected Behavior 

Should not redirect with `&client_id=ghostery`.

### Actual Behavior 

Redirects to login page but with `&client_id=ghostery`. 

### Steps to Reproduce

1. Application with OAuth 2 authentication
2. Use silent authentication with IFrame
3. Wait a little bit

### Versions

+ Browser: Firefox Developer Edition 70.0b14
+ OS: I use Arch btw
+ Extension: 8.4.2
+ Node: *not related*
+ NPM: *not related*

**Comment by christophertino** [comment]
If you see a query string value replaced with `ghostery`, it generally means our anti-tracking has flagged the value as a UUID.  However, it will often catch false positives on development sites because the volume of users is low. This should not be an issue for your application in production. Regardless, please send over the full Azure URL that's being sanitized and we will have a look (remove any IDs, keys, etc before sending). 

For development purposes, I would recommend turning off anti-tracking (the blue shield icon in Ghostery), or whitelist your development test site. If you push the app to production and see the `client_id` still being replaced, let us know so we can look into a whitelist solution for that Azure endpoint.
