### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by ADDISON74** [ghostery/ghostery-extension#481]
### Description
Ghostery is using a lot of RAM. 

### Expected Behavior 
Ghostery should have a reasonable usage. I can accept 100 MB maximum 150 MB.

### Actual Behavior 
In my case it is using about 450 MB and the best value was 326 MB.  

### Steps to Reproduce
1. Chrome latest version on Windows 10 Pro. No other extensions except Ghostery
2. No URL in Address bar just Chrome home page.
3. Shift + Esc to check the memory usage. CPU usage is around 45% (4 cores).

I will disable Ghostery for a while. My machine is only 4 GB of RAM and more than 10% is too much. Usage of CPU is also an issue.

**Comment by suederade** [comment]
I'm getting the same problem except it's using over 2GB of memory.

**Comment by gurgunday** [comment]
Wow.. mine is **much** lower. I'm on Firefox though. Maybe a browser related issue?

**Comment by Zetanova** [comment]
On my chrome it is using 1.5GB, visited only view sites. 

any updates on this issue?

**Comment by christophertino** [comment]
Can you let me know how much Ghostery is consuming in the Chrome Task Manager vs the Windows Task Manager?

**Comment by gilbert-h** [comment]
Just had the same issue. Chrome had it using 3 GB, showed up as ~1.2 GB in Windows task manager. Had less than 10 tabs open, none particularly resource intensive. Windows 10, Chrome 80.0.3987.162, Ghostery 8.4.8

**Comment by Zetanova** [comment]
@christophertino ghostery has 1.5GB under the Chrome-Task-Manager

**Comment by christophertino** [comment]
Can you try manual garbage collection and see if that brings the memory value down? 

- Navigate to chrome://extensions/
- Enable developer mode (top right)
- Under Ghostery click "background page" beside Inspect Views
- Click the Memory tab
- Click the trash icon 3 times, waiting ~3 seconds between each click
- Check Chrome task manager to see if any memory is released

I've been generating heap snapshots and memory allocation profiles but haven't seen anything conclusive.  I was able to see some memory escalation but it seemed to go away after I closed out the developer tools. 

This [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=730437) from the AdBlock team indicates there may be an issue with Chrome delaying garbage collection.  They concluded that the browser may not trigger garbage collection until it runs out of memory (see [here](https://help.getadblock.com/support/solutions/articles/6000087874-adblock-is-using-lots-of-memory)), but that the memory would be freed up eventually. 

If anyone is able to take some heap snapshots (before the memory increase and during), that would be helpful.  From the same Memory tab as above, where it says 'Summary' change that to 'Comparison'. Then sort the columns by # Delta and Size Delta, looking for large positive values.  See if you can drill down into any large values.

**Comment by Zetanova** [comment]
@christophertino Started with 1.2GB memory footprint in the chrome task manager after 5h runtime

JS Heap size was only 20MB and snapshot size too.
The GC only reduced it to 18.5MB 

In the chrome task manager the memory footprint is still at 1.2GB and JS memory 25MB (19MB live)

The Chrome task group has in windows task manager 1.7GB memory

**Comment by JacksonWrath** [comment]
Also seeing this issue lately. Details requested so far:

After a few days use:
Windows Task Manager | RAM
----------------- | -----------------
Chrome Total Usage | 2.1 GB
Ghostery PID Usage | 808 MB

Chrome Task Manager | RAM
--------------- | ----------------
Ghostery | 1.3 GB

Ghostery is the top process by more than 100%. Next step down from there was a tab using about 376 MB (windows reported).

Manual garbage collection only helped by a few MB. Restarting Chrome, Ghostery starts at about 70MB. I took a snapshot after restart; will take another to compare deltas after the problem resurfaces and report back.

**Comment by suederade** [comment]
Here is some data from Chrome Task Manager and Activity Monitor. I also took a sample from Activity Monitor.

Activity Monitor | Memory
-- | --
Base Process | 2.3 GB
Real Memory Size | 1.6 GB
Virtual Memory Size | 25.04 GB
Shared Memory Size | 73.9 MB
Private Memory Size | 1.5 GB


Chrome Task Manager | RAM
-- | --
Ghostery | 2.2 GB

https://drive.google.com/file/d/1GCBCFa3ZxbS6KFRSYshSSFChdQ06UvGz/view?usp=sharing

**Comment by macOneOone** [comment]
Yeah, how that hell happen to a single extension produce 2GB of RAM.
![ghost](https://user-images.githubusercontent.com/16170629/88333747-a5aa2a80-cd28-11ea-997e-b7dbaa8383a1.png)

**Comment by mdnahas** [comment]
I am a casual user of Ghostery (but one with advanced degrees of CS) and I'm seeing extremely high memory usage.  I wouldn't post here, except I saw that the issue was already open.

When I enable Ghostery, the virtual memory used by Firefox's WebExtensions process jumps above 14gb.   When I disable Ghostery, it drops below 1gb.  I found the issue because I was getting lag and Firefox's Memory Report says I'm seeing a lot of "soft page swaps".  I shouldn't see any page swaps --- my machine has 16gb of RAM and I wasn't even doing anything large on it.

I'm shocked how fast virtual memory size jumps up when enabling Ghostery.  Are you mem-mapping a file or using a sparse memory map somewhere?  A memory leak should take time to get to that amount.  It's very odd.

I noticed the lag on my system about 2 to 3 weeks ago.   Tech details are: 

- Firefox 79.0 (64-bit)
- GNOME 3.36.3
- Ubuntu 20.04.1 LTS, 64-bit
- Dell XPS 13 model 9370, 16gb, Intel Core i5-8250U 1.60Ghx x 8

Reply to this message if you need me to do anything to help.

**Comment by christophertino** [comment]
@mdnahas If you're able to run some performance diagnostics it would be helpful. Unfortunately, FF doesn't allow memory snapshots for extensions the same way that Chrome does.  But you can create a performance allocation profile that may be able to show some abnormal memory allocations taking place.  

- Visit about:debugging#/runtime/this-firefox 
- Click "Inspect" next to Ghostery
- In the toolbox window select the Performance tab
- Click the gear icon on the right and enable "Record Allocations"
- Start recording 

There's some additional info from MDN on recording allocations [here](https://developer.mozilla.org/en-US/docs/Tools/Performance/Allocations). I've been chasing this bug for several months without any luck and would be happy to have some extra help tracking this down.

**Comment by mdnahas** [comment]
Ghostery support ("Sloane") contacted me.  They had me update my version of Ghostery and other add-ons, etc.

After doing that, I did some more investigation.  Both Ghostery and HTTPS Everywhere are both allocating about 6.3GB of virtual memory when enabled.  (As measured by the WebExtensions process in the "top" program.)  The other extensions that I use don't do that.  (Those extensions are Disconnect and Leech Block NG.)  

I've learned more about using "top" and can now see the number of page faults in it.  If I encounter the lag again, I'll confirm that it is the WebExtensions process that is faulting and causing the problem.  So far, I've assumed it was Ghostery in Firefox because of the absurdly high amount of virtual memory.  But it seems that is both Ghostery and HTTPS Everywhere extension.

Because you asked, I did a recording while I typed for a minute in GMail.  Hopefully, it helps. (I changed the suffix from .json to .txt, so you'll have to change it back.)

[Ghostery_recording.txt](https://github.com/ghostery/ghostery-extension/files/5057720/Ghostery_recording.txt)

**Comment by christophertino** [comment]
Thanks for that profile. I was seeing something similar on my end around `_scheduleNextTick`.  Could you check one more thing:

- Visit about:debugging#/runtime/this-firefox
- Click "Inspect" next to Ghostery
- In the toolbox window select the Console tab
- Enter `CLIQZ.services.pacemaker.api` and look at the size of the `tasks` object. On my machine the size is 29.

And then let's try turning off Pacemaker:

- Restart FF
- Follow steps above to the Console 
- Enter `CLIQZ.services.pacemaker.unload()`

This may break some things in Ghostery but I'm curious to see if the memory leak is still present.

**Comment by mdnahas** [comment]
CLIQZ.services.pacemaker.api
Object { freq: 1000, timer: 175567, tasks: Set(30) }

At the moment, I'm not sure there is a memory leak.  It takes up 6GB of RAM right away when enabled.  A leak takes time.

I'm hesitant to "break things" when I'm not sure what I'm turning off and don't know how to turn it on and don't know what the lasting effects are.

**Comment by christophertino** [comment]
Pacemaker is just used to schedule timeouts. It will restart when you restart the browser. But I understand if you are hesitant to turn it off. 

Here's an open Bugzilla ticket that seems to be related: [Very high virtual memory usage in the WebExtensions process on Linux](https://bugzilla.mozilla.org/show_bug.cgi?id=1615988)

**Comment by mdnahas** [comment]
That bug report seems to be _exactly_ what I'm seeing in "top".

The lag has reappeared.  I'm not sure what's causing it.  It is not (immediately) connected to the virtual memory issue.  I was able to look at memory faults in "top".  5 processes were experiencing millions of "minor page faults", which happen when the data is already in physical memory but not mapped in the process's memory.  E.g., when a process makes a call to a library function that was previously called by another process.  The most faulted process wasn't even "WebExtensions".

I'm seeing CPU bursts when I encounter the lag.  I'll try to track it down, but it doesn't seem to be connected to this issue.

**Comment by Lagicrus** [comment]
I can also reproduce the same bug with 1GB+ memory usage on the current latest build of Chrome (85) on Windows 10.
Let me know if I can do any testing/recording to narrow this down.

**Comment by Zeldazackman** [comment]
This is still an active issue that has been observed for years, ghostery has been called out as having a memory leak issue in that it can slowly creep to using nearly all of a system's memory despite nothing being used in chrome or firefox.

You can have a single blank tab for the browser and watch it's usage climb higher and higher for no discernable nor logical reason.

**Comment by WesselKroos** [comment]
The extension crashed on my laptop after it reached a memory usage of 5GB. I've restarted it and it's now using 65MB.

**Comment by suederade** [comment]
This is definitely still a problem, and may be even worse. This is 2-3x worse than before. I'm going to have to stop using this until it is addressed.


Activity Monitor | Memory
-- | --
Real Memory Size |  7.04 GB
Virtual Memory Size | 54.51 GB
Shared Memory Size | 185.7 MB
Private Memory Size | 5.04 GB

**Comment by Lagicrus** [comment]
Yeah my solution currently is to just kill it every now and then
Honestly feels like garbage collection is needed or isn't working correctly and something just keeps building up

**Comment by stephanvanhugten** [comment]
My best guess is that Ghostery never releases memory related to blocked requests logging. I observed some websites doing a lot of requests continuously (darned modern websites!) and if the memory is never released it will slowly accumulate in the background.

**Comment by Spongman** [comment]
there's definitely a leak somewhere. i have 1 tab open (this GitHub page):

![image](https://user-images.githubusercontent.com/1088194/153282291-9c9bb6e5-4dfe-4881-bd4a-7c41ccfe719b.png)

**Comment by chrmod** [comment]
Thank you for your report. All of you. We continue to look for a source of the problem.

While this happens, can you please check what Chrome dev-tools for WebExtensions report:
1. go to chrome://extensions/
2. enable "Developer mode"
3. Inspect view: background page of Ghostery
4. Open "Memory" tab
5. Make a screenshot 

Mine look like this:
<img width="453" alt="Screenshot 2022-02-09 at 23 04 40" src="https://user-images.githubusercontent.com/1228153/153297970-f936c076-9234-4c46-8f0f-1dd40bd2f688.png">

Whenever we check, memory usage of the background page is relatively small. The background page is the place that processes all web requests, which would be a prime suspect for memory leaks. 

We've recently posted a question to the Chromium Extensions mailing group https://groups.google.com/a/chromium.org/g/chromium-extensions/c/xSgOd9DGbQw/m/qfsKbwmtAwAJ but honestly speaking, I'm not sure if any of the explanations apply to the problem we witness.

**Comment by Tsovak** [comment]
@chrmod 
hey, I took a snapshot [here](https://cloud.mail.ru/public/7BFq/4kLSV3b1u). Currently, I have 21 tabs, 6 is active, extension memory usage is 2.2Gb constantly.

**Comment by chrmod** [comment]
@Tsovak thank you very much. This is very helpful! 
We have some ideas on what may be happening. Interestingly this does not seem to happen of Firefox, wonder if this may be some edge case in Chromium. 
Anyways the memory dump gave us some hints. Thanks again.

**Comment by ADDISON74** [comment]
I agree @chrmod. Google Chrome is an inexhaustible source of nerves that can lead to pull your hair out of your head. I moved to Edge and I stopped using Ghostery after reporting this issue, I don't know is this issue can be replicated too.

I gave up Chrome because it has a major hardware acceleration issue, on top Nvidia and AMD video cards. When I let all the windows down clicking on Peek in Windows taskbar, it freezes. Then when there were pages with embed movies the screen turns black for a second and the same happens when I close the browser window. I have been reporting these issues for over 1 year and nothing has happened in good. 

If anyone is facing this issue I would recommend to disable hardware acceleration or in chrome://flags search for "Choose ANGLE graphics backend" and set the value from Default to OpenGL.

**Comment by philipp-classen** [comment]
@Tsovak Thanks for the snapshot! I'm was able to produce the high memory usage on Chrome and my heap summary looked almost identical (`Window#DocumentCachedAccessor` holding references). It is not clear yet how to fix it, but we reached now a stage where the problem is clearly reproducible on Chrome.

---

(Chrome specific from here on) One aspect that I'm currently not fully understand is whether the entries in `Window#DocumentCachedAccessor` will be cleared by the GC if there is no memory pressure. At least on my machine, there is typically enough idle memory to justify keeping the entries in the cache alive. (It would be interesting to test more on a constrained environment instead of a dev machine with lots of memory.)

DocumentCachedAccessor is part of the Blink render engine:
https://chromium.googlesource.com/chromium/src/+/HEAD/third_party/blink/renderer/platform/bindings/v8_private_property.h#127

And the class `ScopedPersistent` is defined here:
https://chromium.googlesource.com/chromium/src/+/HEAD/third_party/blink/renderer/platform/bindings/scoped_persistent.h#39

From the comments (and the name "cache"), it could be that Chrome is not aggressively cleaning up the values in the cache if there is enough memory available on the system. But, of course, it could also be that the extension keeps references alive in some callbacks. We will have to debug more into that.

**Comment by Kumirei** [comment]
> From the comments (and the name "cache"), it could be that Chrome is not aggressively cleaning up the values in the cache if there is enough memory available on the system

For what it's worth my system eventually runs out of memory and freezes. I am uninstalling this extension though, so I will not be able to help debug.

**Comment by philipp-classen** [comment]
We are still looking into finding a solution, but a reliable path to reproduce on Chrome is as follows (tested on MacOS and Linux):

* Open a YouTube page
* After a few seconds, jump to the next YouTube video
* Repeat that with 10 to 20 pages (the memory usages in Window#DocumentCachedAccessor should now be constantly going up)
