### ISSUE TITLE
Add option to whitelist website from adblocking but not from anti tracking

### ISSUE THREAD

**Issue by ghost** [ghostery/ghostery-extension#493]
Please add the option so users can whitelist websites from the adblocking feature individually (so I can support them with advertising) but keep the anti tracking protection enabled (so private data points are anonymized from networks requests). Basically I am asking for the option to use the adblocking and anti tracking tools of Ghostery on a per website case instead of the actual on/off for all pages

Currently you can trust a website but that unblock all blocking behaviour thus removing also the privacy protection. The other option is whitelisting trackers individually per websites but this has 2 problems: 

1) You need to manually whitelist dozens of trackers on each website which is cumbersome
2) The above problem requires users to be familiar with which trackers are advertising and which are privacy invasive. Most people don`t know that

I also would like to jump on the wagon requesting these feature as well #148 
These options would give users even more choice and control of their browser experience

Thanks

**Comment by gurgunday** [comment]
This is a great feature to have and one I had opened an issue about before even checking it here. Since mine is closed now I just want to add something here.

Having an option to disable blocking in terms of ads and trackers but **not** anti tracking would put Ghostery in a unique position among other privacy/adblock extensions that just have an all or nothing approach in terms of blocking ads and trackers. It would also benefit website owners that the user chooses to help/support since they could get their analytics and ad revenue, just like in Cliqz Browser. This might require a more aggressive cookie blocking (which I already think is necessary since Firefox for example already blocks a good amount of them now) but anti-tracking can easily handle it. Plus doing it like in the browser where when you disable adblock for example it asks if you want to disable it for the current domain or for all of them makes a lot of sense.

**Comment by christophertino** [comment]
I like this option too. The difficulty will be implementing it in such a way that it's clear to the user.

**Comment by grgnday** [comment]
@christophertino My suggestion is to just remove the "trust site" button altogether (Pause Ghostery is fine), and like in Cliqz Browser, when you click on the Enhanced Ad Blocking button let it ask if it should apply globally or for the current site. Also, for Anti Tracking and Smart Blocking.

**Comment by yokoffing** [comment]
> @christophertino My suggestion is to just remove the "trust site" button altogether (Pause Ghostery is fine), and like in Cliqz Browser, when you click on the Enhanced Ad Blocking button let it ask if it should apply globally or for the current site. Also, for Anti Tracking and Smart Blocking.

I think this is a fantastic suggestion!

**Comment by smalluban** [comment]
Major platforms migrated to v10. Feel free to re-open if the issue is still valid.
