### ISSUE TITLE
The New Yorker: Annoying Banner

### ISSUE THREAD

**Issue by yokoffing** [ghostery/ghostery-extension#504]
### Description
The New Yorker has an annoying banner that takes up half the page when you click on an article asking the user to subscribe. Please remove.

### Expected Behavior 

Force Ghostery to hide the banner.

### Steps to Reproduce

1. Go to `https://www.newyorker.com/`
2. Click on any article.
3. https://postimg.cc/yWGFVxdt

### Versions
Applies to any browser, but here is my configuration:
+ Browser: Firefox 73.0.1 (current stable release); Ghostery is set to block everything in all categories provided.
+ OS: macOS 10.15.3
+ Node:
+ NPM:

**Comment by hjstephens09** [comment]
Using [Bypass Paywalls Clean](https://github.com/magnolia1234/bypass-paywalls-firefox-clean) gets rid of this issue, but it'd be preferred for Ghostery to add a cosmetic filter to deal with this outside of using another extension.

**Comment by remusao** [comment]
Hi @hjstephens09,

Thank you so much for taking the time to open an issue. This feature request is related to another discussion in the past (you can find the ticket here: https://github.com/ghostery/ghostery-extension/issues/22). I think it would be worth discussing this seriously again and maybe consider including this in next Ghostery release. @christophertino what do you think?

**Comment by hjstephens09** [comment]
So, every three months or so, I check on Ghostery and test it out on Firefox and Chrome, and usually tinker with the CLIQZ browser too. Despite the advantages of speed and technology I get with using Ghostery over uBlock Origin, I am always disappointed with the amount of annoyances I run into using just Ghostery. (The same can be said for the Brave browser shields, in this case).

[Rémi stated last year](https://github.com/ghostery/ghostery-extension/issues/22#issuecomment-526841301) that:
> ... not allowing arbitrary lists in Ghostery at the moment allows us to make sure features behave optimally and do not conflict with each other. For example, the blocking lists used by default in the adblocker are selected and optimized so that they play well with our AI anti-tracking technology.

I love that Ghostery optimizes its AI anti-tracking technology and adblocker to work nicely together. So instead of allowing random blocklists, why not incorporate Fanboy Annoyances, uBlock Annoyances, and AdGuard annoyances into Ghostery? Filter them for obsolete code and interferences with the anti-tracking technology. Make sure everything plays nicely. Then ship it in Ghostery as an "Anti-Annoyances" category. You could leave it off by default just as you do with other categories upon installation. But an in-demand feature is there, and now one can browse webpages smoothly.

(I wouldn't mind the devs allowing user to add their own custom filters, too. But I think the demand for custom filters will be much less if you implement something like I describe in the paragraph above.)

**Allow me to speak as a consumer.** I am frustrated with my experiences in Ghostery on Firefox or Chrome, and it comes down to two main reasons: 1) the inability to block annoyances and, similarly, 2) inability to block pop-under ads. I can do both of these on uBlock Origin: the former by checking annoyances lists; the latter by toggling the `Click to disable all popups` button on a per-site basis (useful for adult content sites with lots of pop-unders ads when clicking the video). I still can't do either on the Brave browser, which also focuses on third-party ads / scripts and not first-party, but I do find it catches some annoyances at random sometimes that Ghostery doesn't block all.

uBlock Origin may be _only_ a blocklist apporach but I hardly ever run into issues or annoyances in day-to-day browsing, whereas with Ghostery I still run into anti-adblocking scripts (e.g., CNN), page banners that take up half the page (e.g., The Guardian), and GDRP / cookie notices (most websites).

I like the Ghostery brand. I consider myself an advanced enduser who is optimistic about the sanitizing / heuristic approach to combat ads and tracking. And what I want the people up top to hear is: _I want Ghostery to succeed. I want to support you._  I've spoken with support a few times now when I run into issues, and I am told to either disable enhanced adblocking or that annoyance features aren't supported.

If Ghostery implement an anti-annoyance mode that is effective, I would switch from uBlock Origin and AdGuard [for Safari] in a heartbeat for Ghostery's AI anti-tracking technology. And it would be much easier to win over a lot of my peers.

Thanks for all your work,

Hal

@remusao @christophertino

**Comment by yokoffing** [comment]
Every since Ghostery added the Annoyance option (#527 ), this is no longer an issue. Thank you for finally implementing this! I've noticed a great many adblock blockers / notices and pop-ups since the update.

In the future, it would also be nice to be able to block social media widgets on page as the part of "annoyances." Outside of this, the web is much more usable with the annoyance feature implemented. Thank you for listening to the users!
