### ISSUE TITLE
Discussion: Full Third-Party Cookie Blocking

### ISSUE THREAD

**Issue by grgnday** [ghostery/ghostery-extension#516]
### Description
Apple's Safari has started to [fully block third party cookies by default](https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/). It is funny because Cliqz did this years ago with their products and called this "a simple approach". Now I don't know how much it will take Firefox or others to follow up but Safari doing it should be able to force the majority of websites to become compatible with the update.

As Firefox _already_ blocks a _big chunk_ of third party cookies, maybe Ghostery should be the extension to take it one step further and implement this as anyone who installs an extension to further their privacy should expect this kind of protection. Or maybe, waiting for other browsers to take action would be the better thing to do as then you wouldn't have to modify your code for anti-tracking multiple times. What do you think?

Edit: I've seen the recent update to the browser-core which makes cookie blocking more aggressive. IMO fully blocking them should still be discussed.

**Comment by sammacbeth** [comment]
Switching Ghostery to full 3rd party cookie blocking (with some compatibility exceptions) is simple - there is a config option in enhance anti-tracking to do this. I'm not sure we'd be able to turn this on for all users at present because of the amount of sites it breaks. Hopefully Safari's changes will help improve this situation though. We cloud look at exposing this as a setting for users who want that extra protection though (cc @christophertino).

Note, however, that Ghostery cookie blocking is limited to HTTP cookies. At the moment we do not block cookies created from DOM APIs (i.e. `document.cookie`). This is because webextension API limitations make it difficult to do this properly while including other Ghostery features such as per site and per tracker whitelisting. Upcoming changes to extension APIs in chrome may also make what we do at present [no longer possible](https://whotracks.me/blog/manifest_v3_privacy.html) there.

All browsers do support native 3rd party cookie blocking though, which will block the DOM cookie API, and also `localStorage` and `indexedDB` in 3rd party contexts. This is however at the cost of  being able to whitelist specific sites, or benefit from the compatibility rules and heuristics we use in Cliqz and Ghostery to prevent things like OAuth logins and [Office365](https://whotracks.me/blog/block-third-party-cookies.html) from breaking.

**Comment by grgnday** [comment]
After Safari's strict change I wonder what Office 365 and others will do. You are probably right saying we should wait and see how it plays out long-term. I doubt Mozilla will stick with their "curated" list after such moves by other "for-profit" companies like Apple and Brave. They could though.

For Ghostery, honestly, I didn't know how these settings would affect other modules. Even though I would love to see it become the extension version of Cliqz Browser, not being able to fully achieve that is probably the reason why you started building your own browser and Ghostery's purpose was and still is different. As long as it strips out PII from third party requests with anti-tracking, I'm fine with it giving compromises.

Even though this is not the right mentality to have, I myself hate Chrome and would be happy to see them hurting their market share by being so bad at protecting people's privacy.

**Comment by grgnday** [comment]
@sammacbeth Quick question then, if I set Firefox to block third party cookies, will that affect Ghostery's heuristics for anti-tracking? (Not talking about cookie blocking obviously but the PII removal.)

**Comment by sammacbeth** [comment]
> @sammacbeth Quick question then, if I set Firefox to block third party cookies, will that affect Ghostery's heuristics for anti-tracking? (Not talking about cookie blocking obviously but the PII removal.)

No. The unsafe data removal system runs irrespective of cookie setting.

**Comment by grgnday** [comment]
Hey @sammacbeth, I did set Firefox to block all third party cookies which also broke Ghostery's login functions in the sense that it logged me out from the extension and even if I log in it instantly logs out. You think this is fixable?

**Comment by christophertino** [comment]
You'll need to set an exception in FF to fix this.  From about:preferences#privacy > Cookies & Site Data > Manage Exceptions > Manage Permissions > Add an "Allow" exception for https://consumerapi.ghostery.com

**Comment by grgnday** [comment]
Thanks for your help. Closing the issue for now then. If someone’s gonna take this step first, it should be the browsers anyway.
