### ISSUE TITLE
Keep on pause after browser restart

### ISSUE THREAD

**Issue by newsjunkie247** [ghostery/ghostery-extension#709]
### Description
I would like to be able to keep the extension on pause when I restart my browser so I can still see trackers without necessarily blocking them/or interfering with page loads when trust site doesn't work. 
### Expected Behavior

Extension should stay paused on restart

### Actual Behavior

Extension turns back on when I restart the browser

### Steps to Reproduce

Switch to pause, exit browser, restart, extension turns back on. 
### Versions

+ Browser: Firefox/Waterfox
+ OS:Windows 
+ Node:
+ NPM:

**Comment by christophertino** [comment]
Sorry for the delay. For privacy purposes, the pause feature is intended to be per session only. Otherwise, a user may forget that they paused Ghostery and remain unprotected indefinitely. If you're interested in using Ghostery as a diagnostic tool, open Settings > Global Blocking and unblock all of the categories. You should also turn off Ad Blocking and Anti-Tracking from the main panel.

**Comment by chrmod** [comment]
Agreeing with Chis here.
