### ISSUE TITLE
Bad readability of tracker counter of toolbar icon in dark mode.

### ISSUE THREAD

**Issue by mbuening** [ghostery/ghostery-extension#790]
### Description

The readability of the tracker counter batch of Ghostery's toolbar icon is bad when the browser uses a dark appearance theme.

### Expected Behavior

Better readability of toolbar icon's tracker counter batch by using a more suitable foreground colour when the browser uses a dark appearance theme.

### Actual Behavior

When the browser is using a dark appearance theme the tracker counter batch of Ghostery's toolbar icon is almost unreadable:
<img width="46" alt="Screenshot 2022-05-27 at 17 40 16" src="https://user-images.githubusercontent.com/100283377/170734842-914185ad-1548-4e0a-be60-32705b1e28e3.png">

### Steps to Reproduce

1. Activate dark appearance theme in the browsers settings.
2. Visit a web site with trackers.

### Versions

+ Browser: Brave Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (x86_64)
+ OS: MacOS 10.14.6

**Comment by smalluban** [comment]
@mbuening Thanks for rising the issue. After the investigation, it looks that it is a regression of the Chrome Browser, which is already fixed, and for sure included in the upcoming 103 version. 

In short, the Chrome API calculates the color of the text automatically based on the background color, which is in the 102 version is broken and always fixed to white (in light mode) and dark gray (in dark mode).

Sorry for the inconvenience, but there is not much we can do about it right now, as fixing this bug here could potentially make a regression in other browsers, which work correctly.
