### ISSUE TITLE
Ghostery preventing bfcache from working (due to using an unload handler)

### ISSUE THREAD

**Issue by chrisblakley** [ghostery/ghostery-extension#836]
### Description

bfcache (Back/Forward Cache) is a fairly new tech that allows the browser's back button to instantly restore the state of the previous page (rather than the prior method of actually reloading the page). However, for bfcache to work, the website must not use unload handlers (including browser extensions).

**Running a bfcache test from Chrome 104 DevTools**
The Application tab and Back/Forward cache pane shows the bfcache is failing due to an unload handler
![Screen Shot 2022-08-17 at 8 49 34 AM](https://user-images.githubusercontent.com/6349678/185135566-fcbe6188-183d-4422-879d-326214e90524.png)

When deactivating Ghostery, the bfcache works successfully:

![Screen Shot 2022-08-17 at 8 46 22 AM](https://user-images.githubusercontent.com/6349678/185136531-7b7a05ec-e224-473f-9559-728776ef8860.png)

![Screen Shot 2022-08-17 at 8 46 43 AM](https://user-images.githubusercontent.com/6349678/185136629-6fc30f42-373d-4d96-bd58-c0da92dce206.png)

More information about bfcache here: https://web.dev/bfcache/
Section related to avoiding the use of unload handlers: https://web.dev/bfcache/#never-use-the-unload-event

> Instead of using the unload event, use the pagehide event. The pagehide event fires in all cases where the unload event currently fires, and it also fires when a page is put in the bfcache.

### Expected Behavior

When using the back button, or when testing bfcache from Chrome DevToos > Application > Back/forward cache, the previous page should restore instantly.

### Actual Behavior

The previous page must reload completely because of an unload handler in Ghostery.

### Steps to Reproduce

1. In Chrome 98+ (I am using v104), go to a website that is known to not have an unload handler. In my case I am using https://nebula.gearside.com/
2. Open Chrome DevTools and select the Application tab
3. In the left side, choose the "Back/forward cache" page
4. Click the "Test back/forward cache" button
5. If Ghostery is enabled, a message that says "The page has an unload handler in the main frame." which indicates a failed test.
6. If Ghostery is deactivated (or not installed), the error message will not appear and a green checkmark will show success of bfcache.

### Versions

+ Browser: Chrome 104
+ OS: Mac 12.5
+ Node: n/a
+ NPM: n/a

**Comment by chrisblakley** [comment]
It appears the two files that include `unload` in Ghostery are:
- https://github.com/ghostery/ghostery-extension/blob/main/extension-manifest-v2/src/classes/Module.js
- https://github.com/ghostery/ghostery-extension/blob/main/extension-manifest-v2/src/classes/SearchMessager.js

**Comment by philipp-classen** [comment]
Thanks for reporting! Will have to test if it breaks something to use `pagehide` instead of `unload`.

Looking through the code, I found these places:
* https://github.com/ghostery/common/blob/f1d4bcf465540c879185ba9c512291c11382bc53/modules/core/sources/content.es#L174
* https://github.com/ghostery/common/blob/f1d4bcf465540c879185ba9c512291c11382bc53/modules/core/sources/content/run.es#L103
* https://github.com/ghostery/common/blob/f1d4bcf465540c879185ba9c512291c11382bc53/modules/webextension-specific/sources/app.bundle.es#L61
* https://github.com/ghostery/common/blob/f1d4bcf465540c879185ba9c512291c11382bc53/modules/human-web/sources/content.es#L206

The other places are in integration tests:
* https://github.com/ghostery/common/blob/f1d4bcf465540c879185ba9c512291c11382bc53/modules/webrequest-pipeline/tests/integration/webrequest-pipeline-test.es#L263
* https://github.com/ghostery/common/blob/f1d4bcf465540c879185ba9c512291c11382bc53/modules/webrequest-pipeline/tests/integration/webrequest-pipeline-test.es#L339

Maybe there are more.

**Comment by philipp-classen** [comment]
Wow, the performance boost in some examples is quite nice!

For example:
* Do a search on Brave or Ghostery Search and click on a Wikipedia result
* Normally navigating back and forth takes a bit of time, but now it is instant (tested on Chrome and Firefox)

**Comment by chrmod** [comment]
We've started the rollout of this fix in 8.9.x line. Thank you for your help @chrisblakley !
