### ISSUE TITLE
Can't Edit Ghostery Settings 

### ISSUE THREAD

**Issue by akano12** [ghostery/ghostery-extension#962]
I've had this issue since 8.9.6, the settings option under Ghostery in Firefox mobile has disappeared.
I can install Ghostery but there's no way for me to select what to block or allow, i was expecting something like pop up to appear after installation but nothing happens.

Edit: Also read the changlogs, searched in closed issues for something similar but didn't find anything related to this

![Screenshot_20221216-011232_Firefox.jpg](https://user-images.githubusercontent.com/50032603/207986756-69da3769-c9e0-47c3-a06d-7586b4f00ab7.jpg)

**Comment by sghostt** [comment]
Hey @akano12. In order to view the Ghostery Control Panel in the Firefox mobile browser app, press the kebab > press "Add-ons" > Press Ghostery. Here you can enable and interact with the Ghostery Control Panel settings. If you do not see Ghostery, press "Add-ons Manager" and we should be around number 4 on the suggested list. Otherwise, install via the Firefox Add-on store by searching for Ghostery. If you have any questions, please shoot us an email at support@ghostery.com so we can assist. Thanks for using Ghostery :)

**Comment by akano12** [comment]
> Hey @akano12. In order to view the Ghostery Control Panel in the Firefox mobile browser app, press the kebab > press "Add-ons" > Press Ghostery. Here you can enable and interact with the Ghostery Control Panel settings. If you do not see Ghostery, press "Add-ons Manager" and we should be around number 4 on the suggested list. Otherwise, install via the Firefox Add-on store by searching for Ghostery. If you have any questions, please shoot us an email at support@ghostery.com so we can assist. Thanks for using Ghostery :)

Yea that did the trick thanks. But may i ask why was this changed to be that way?

**Comment by akano12** [comment]
Just to clarify some things:
-When installing Ghostery, there's no prompt.
-Even in add-ons page there's no way to interact with Ghostery (screenshot above) 
-The only way to edit Ghostery settings is by visiting a website then doing what was suggested above. (kebab menu->add-ons). Because only active add-ons on this website will be shown (like Ghostery)
