### ISSUE TITLE
Remove dependency `lodash-es`

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#977]
In MV3 we only use `throttle` once in here https://github.com/ghostery/ghostery-extension/blob/455a51f087084baa7885557c00513ee2cf1c2568/extension-manifest-v3/src/background/tab-stats.js#L20

If we replace it with something simple like:
```js
const throttle = (fn, delay) => {
  let lastCalled = 0;
  return (...args) => {
    let now = Date.now();
    if(now - lastCalled < delay) {
      return;
    }
    lastCalled = now;
    return fn(...args);
  }
}
```
we could remove `loadsh` from dependency list.

**Comment by philipp-classen** [comment]
I think, the semantic of `throttle` is a bit more complex: https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L10897

Switching to `throttle` was a simplification since it replaced the original code where I unintentionally reinvented the wheel (was only aware of `debounce`) here: https://github.com/ghostery/ghostery-dnr-extension/commit/f61cfc45772f6983a1a3db995949befaac9b442e

But the old, more verbose code shows a bit the semantic that was intended.

Since `throttle` is what we want to use, maybe we can keep it as is, but only import a specialized Lodash version? Something like that: https://www.npmjs.com/package/lodash.throttle
